.\"/*-
.\" * Copyright (c) 1999-2003 MAEKAWA Masahide <gehenna@daemon-systems.org>
.\" * All rights reserved.
.\" *
.\" * Redistribution and use in source and binary forms, with or without
.\" * modification, are permitted provided that the following conditions
.\" * are met:
.\" * 1. Redistributions of source code must retain the above copyright
.\" *    notice, this list of conditions and the following disclaimer.
.\" * 2. Redistributions in binary form must reproduce the above copyright
.\" *    notice, this list of conditions and the following disclaimer in the
.\" *    documentation and/or other materials provided with the distribution.
.\" *
.\" * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" * SUCH DAMAGE.
.\" *
.\" *	$Id: udesc_dump.8,v 1.7 2003/01/11 14:46:36 maekawa Exp $
.\" */
.Dd December 11, 2003
.Dt UDESC_DUMP 8
.Os
.Sh NAME
.Nm udesc_dump
.Nd show USB descriptors
.Sh SYNOPSIS
.Nm udesc_dump
.Op /dev/ugen?
.Sh DESCRIPTION
.Nm udesc_dump
shows USB descriptors.
.Sh SUPPORTED DESCRIPTORS
Device descriptor
.Pp
Configuration descriptor
.Pp
Interface descriptor
.Pp
Interface Power descriptor
.Pp
Endpoint descriptor
.Pp
String descriptor
.Pp
Audio Class descriptors
.Pp
HID descriptor
.Pp
Report descriptor
.Sh SEE ALSO
.Xr usb 4 ,
.Xr ugen 4 ,
.Xr uhid 4
.Sh AUTHORS
.An MAEKAWA Masahide
.An UCHIYAMA Yasushi
