/*	$Id: hiddefs_data.h,v 1.5 2002/12/03 16:10:33 maekawa Exp $	*/

/*
 * THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
 *
 * generated from:
 *	Id: hiddefs,v 1.2 2002/12/03 16:10:22 maekawa Exp 
 */

/*
 * Item Table
 */
struct hid_item {
	uint8_t		type;
	uint8_t		tag;
	const char	*name;
};

struct hid_item hid_items[] = {
	{
		HID_ITEM_TYPE_MAIN,
		HID_MAIN_ITEM_INPUT,
		"Input",
	},
	{
		HID_ITEM_TYPE_MAIN,
		HID_MAIN_ITEM_OUTPUT,
		"Output",
	},
	{
		HID_ITEM_TYPE_MAIN,
		HID_MAIN_ITEM_COLLECTION,
		"Collection",
	},
	{
		HID_ITEM_TYPE_MAIN,
		HID_MAIN_ITEM_FEATURE,
		"Feature",
	},
	{
		HID_ITEM_TYPE_MAIN,
		HID_MAIN_ITEM_ENDCOLLECTION,
		"End Collection",
	},
	{
		HID_ITEM_TYPE_GLOBAL,
		HID_GLOBAL_ITEM_USAGE_PAGE,
		"Usage Page",
	},
	{
		HID_ITEM_TYPE_GLOBAL,
		HID_GLOBAL_ITEM_LOGICAL_MIN,
		"Logical Minimum",
	},
	{
		HID_ITEM_TYPE_GLOBAL,
		HID_GLOBAL_ITEM_LOGICAL_MAX,
		"Logical Maximum",
	},
	{
		HID_ITEM_TYPE_GLOBAL,
		HID_GLOBAL_ITEM_PHYSICAL_MIN,
		"Physical Minimum",
	},
	{
		HID_ITEM_TYPE_GLOBAL,
		HID_GLOBAL_ITEM_PHYSICAL_MAX,
		"Physical Maximum",
	},
	{
		HID_ITEM_TYPE_GLOBAL,
		HID_GLOBAL_ITEM_UNIT_EXPONENT,
		"Unit Exponent",
	},
	{
		HID_ITEM_TYPE_GLOBAL,
		HID_GLOBAL_ITEM_UNIT,
		"Unit",
	},
	{
		HID_ITEM_TYPE_GLOBAL,
		HID_GLOBAL_ITEM_REPORT_SIZE,
		"Report Size",
	},
	{
		HID_ITEM_TYPE_GLOBAL,
		HID_GLOBAL_ITEM_REPORT_ID,
		"Report ID",
	},
	{
		HID_ITEM_TYPE_GLOBAL,
		HID_GLOBAL_ITEM_REPORT_COUNT,
		"Report Count",
	},
	{
		HID_ITEM_TYPE_GLOBAL,
		HID_GLOBAL_ITEM_PUSH,
		"Push",
	},
	{
		HID_ITEM_TYPE_GLOBAL,
		HID_GLOBAL_ITEM_POP,
		"Pop",
	},
	{
		HID_ITEM_TYPE_LOCAL,
		HID_LOCAL_ITEM_USAGE,
		"Usage",
	},
	{
		HID_ITEM_TYPE_LOCAL,
		HID_LOCAL_ITEM_USAGE_MIN,
		"Usage Minimum",
	},
	{
		HID_ITEM_TYPE_LOCAL,
		HID_LOCAL_ITEM_USAGE_MAX,
		"Usage Maximum",
	},
	{
		HID_ITEM_TYPE_LOCAL,
		HID_LOCAL_ITEM_DESIGNATOR_INDEX,
		"Designator Index",
	},
	{
		HID_ITEM_TYPE_LOCAL,
		HID_LOCAL_ITEM_DESIGNATOR_MIN,
		"Designator Minimum",
	},
	{
		HID_ITEM_TYPE_LOCAL,
		HID_LOCAL_ITEM_DESIGNATOR_MAX,
		"Designator Maximum",
	},
	{
		HID_ITEM_TYPE_LOCAL,
		HID_LOCAL_ITEM_STRING_INDEX,
		"String Index",
	},
	{
		HID_ITEM_TYPE_LOCAL,
		HID_LOCAL_ITEM_STRING_MIN,
		"String Minimum",
	},
	{
		HID_ITEM_TYPE_LOCAL,
		HID_LOCAL_ITEM_STRING_MAX,
		"String Maximum",
	},
	{
		HID_ITEM_TYPE_LOCAL,
		HID_LOCAL_ITEM_DELIMITER,
		"Usage Modifier Control",
	},
	{ 0xff, 0xff, NULL, }
};

/*
 * Collection Table
 */
struct hid_collection {
	uint8_t		type;
	const char	*name;
};

struct hid_collection hid_collections[] = {
	{
		HID_COLLECTION_PHYSICAL,
		"Physical",
	},
	{
		HID_COLLECTION_APPLICATION,
		"Application",
	},
	{
		HID_COLLECTION_LOGICAL,
		"Logical",
	},
	{
		HID_COLLECTION_VENDOR_START,
		"",
	},
	{
		HID_COLLECTION_VENDOR_END,
		"",
	},
	{ 0xff, NULL, }
};

/*
 * Usage Page Table
 */
struct hid_usage_page {
	uint16_t	page;
	const char	*name;
};

struct hid_usage_page hid_usage_pages[] = {
	{
		HID_USAGE_PAGE_UNDEFINED,
		"Undefined",
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		"Generic Desktop Controls",
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		"Simulation Controls",
	},
	{
		HID_USAGE_PAGE_VR,
		"VR Controls",
	},
	{
		HID_USAGE_PAGE_SPORTS,
		"Sports Controls",
	},
	{
		HID_USAGE_PAGE_GAME,
		"Game Controls",
	},
	{
		HID_USAGE_PAGE_KEYBOARD,
		"Keyboard/Keypad",
	},
	{
		HID_USAGE_PAGE_LED,
		"LEDs",
	},
	{
		HID_USAGE_PAGE_BUTTON,
		"Button",
	},
	{
		HID_USAGE_PAGE_ORDINAL,
		"Ordinal",
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		"Telephony",
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		"Consumer",
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		"Digitizer",
	},
	{
		HID_USAGE_PAGE_PID,
		"PID Page",
	},
	{
		HID_USAGE_PAGE_UNICODE,
		"Unicode",
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		"Alphanumeric Display",
	},
	{
		HID_USAGE_PAGE_MONITOR1,
		"Monitor pages",
	},
	{
		HID_USAGE_PAGE_MONITOR2,
		"Monitor pages",
	},
	{
		HID_USAGE_PAGE_MONITOR3,
		"Monitor pages",
	},
	{
		HID_USAGE_PAGE_MONITOR4,
		"Monitor pages",
	},
	{
		HID_USAGE_PAGE_POWER1,
		"Power pages",
	},
	{
		HID_USAGE_PAGE_POWER2,
		"Power pages",
	},
	{
		HID_USAGE_PAGE_POWER3,
		"Power pages",
	},
	{
		HID_USAGE_PAGE_POWER4,
		"Power pages",
	},
	{
		HID_USAGE_PAGE_BARCODE,
		"Bar Code Scanner page",
	},
	{
		HID_USAGE_PAGE_WEIGHING,
		"Weighing Devices page",
	},
	{
		HID_USAGE_PAGE_CAMERA,
		"Camera Control Page",
	},
	{
		HID_USAGE_PAGE_ARCADE,
		"Arcade Page",
	},
	{
		HID_USAGE_PAGE_VENDOR_START,
		"",
	},
	{
		HID_USAGE_PAGE_VENDOR_END,
		"",
	},
	{ 0xffff, NULL, }
};

/*
 * Usage Table
 */
struct hid_usage {
	uint16_t	page;
	uint16_t	usage;
	const char	*name;
	uint32_t	type;
};

struct hid_usage hid_usages[] = {
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0000, "Undefined",
		NONE,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0001, "Pointer",
		CP,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0002, "Mouse",
		CA,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0004, "Joystick",
		CA,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0005, "Game Pad",
		CA,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0006, "Keyboard",
		CA,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0007, "Keypad",
		CA,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0008, "Multi-axis Controller",
		CA,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0030, "X",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0031, "Y",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0032, "Z",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0033, "Rx",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0034, "Ry",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0035, "Rz",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0036, "Slider",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0037, "Dial",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0038, "Wheel",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0039, "Hat Switch",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x003a, "Counted Buffer",
		CL,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x003b, "Byte Count",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x003c, "Motion Wakeup",
		OSC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x003d, "Start",
		OOC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x003e, "Select",
		OOC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0040, "Vx",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0041, "Vy",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0042, "Vz",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0043, "Vbrx",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0044, "Vbry",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0045, "Vbrz",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0046, "Vno",
		DV,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0080, "System Control",
		CA,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0081, "System Power Down",
		OSC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0082, "System Sleep",
		OSC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0083, "System Wake Up",
		OSC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0084, "System Context Menu",
		OSC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0085, "System Main Menu",
		OSC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0086, "System App Menu",
		OSC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0087, "System Menu Help",
		OSC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0088, "System Menu Exit",
		OSC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0089, "System Menu Select",
		OSC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x008a, "System Menu Right",
		RTC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x008b, "System Menu Left",
		RTC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x008c, "System Menu Up",
		RTC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x008d, "System Menu Down",
		RTC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0091, "D-pad Up",
		OOC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0092, "D-pad Down",
		OOC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0093, "D-pad Right",
		OOC,
	},
	{
		HID_USAGE_PAGE_GENERICDESKTOP,
		0x0094, "D-pad Left",
		OOC,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0000, "Undefined",
		NONE,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0001, "Flight Simulation Device",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0002, "Automobile Simulation Device",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0003, "Tank Simulation Device",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0004, "Spaceship Simulation Device",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0005, "Submarine Simulation Device",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0006, "Sailing Simulation Device",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0007, "Motorcycle Simulation Device",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0008, "Sports Simulation Device",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0009, "Airplane Simulation Device",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x000a, "Helicopter Simulation Device",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x000b, "Magic Carpet Simulation Device",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x000c, "Bicycle Simulation Device",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0020, "Flight Control Stick",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0021, "Flight Stick",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0022, "Cyclic Control",
		CP,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0023, "Cyclic Trim",
		CP,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0024, "Flight Yoke",
		CA,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x0025, "Track Control",
		CP,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00b0, "Aileron",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00b1, "Aileron Trim",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00b2, "Anti-Torque Control",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00b3, "Autopilot Enable",
		OOC,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00b4, "Chaff Release",
		OSC,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00b5, "Collective Control",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00b6, "Dive Brake",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00b7, "Electronic Countermeasures",
		OOC,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00b8, "Elevator",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00b9, "Elevator Trim",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00ba, "Rudder",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00bb, "Throttle",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00bc, "Flight Communications",
		OOC,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00bd, "Flare Release",
		OSC,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00be, "Landing Gear",
		OOC,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00bf, "Toe Brake",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00c0, "Trigger",
		MC,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00c1, "Weapons Arm",
		OOC,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00c2, "Weapons Select",
		OSC,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00c3, "Wing Flaps",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00c4, "Accelerator",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00c5, "Brake",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00c6, "Clutch",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00c7, "Shifter",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00c8, "Steering",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00c9, "Turret Direction",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00ca, "Barrel Elevation",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00cb, "Dive Plane",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00cc, "Ballast",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00cd, "Bicycle Crank",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00ce, "Handle Bars",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00cf, "Front Brake",
		DV,
	},
	{
		HID_USAGE_PAGE_SIMULATION,
		0x00d0, "Rear Brake",
		DV,
	},
	{
		HID_USAGE_PAGE_VR,
		0x0000, "Undefined",
		NONE,
	},
	{
		HID_USAGE_PAGE_VR,
		0x0001, "Belt",
		CA,
	},
	{
		HID_USAGE_PAGE_VR,
		0x0002, "Body Suit",
		CA,
	},
	{
		HID_USAGE_PAGE_VR,
		0x0003, "Flexor",
		CP,
	},
	{
		HID_USAGE_PAGE_VR,
		0x0004, "Glove",
		CA,
	},
	{
		HID_USAGE_PAGE_VR,
		0x0005, "Head Tracker",
		CP,
	},
	{
		HID_USAGE_PAGE_VR,
		0x0006, "Head Mounted Display",
		CA,
	},
	{
		HID_USAGE_PAGE_VR,
		0x0007, "Hand Tracker",
		CA,
	},
	{
		HID_USAGE_PAGE_VR,
		0x0008, "Oculometer",
		CA,
	},
	{
		HID_USAGE_PAGE_VR,
		0x0009, "Vest",
		CA,
	},
	{
		HID_USAGE_PAGE_VR,
		0x000a, "Animatronic Device",
		CA,
	},
	{
		HID_USAGE_PAGE_VR,
		0x0020, "Stereo Enable",
		OOC,
	},
	{
		HID_USAGE_PAGE_VR,
		0x0021, "Display Enable",
		OOC,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0001, "Baseball Bat",
		CA,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0002, "Golf Club",
		CA,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0003, "Rowing Machine",
		CA,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0004, "Treadmill",
		CA,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0030, "Oar",
		DV,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0031, "Slope",
		DV,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0032, "Rate",
		DV,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0033, "Stick Speed",
		DV,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0034, "Stick Face Angle",
		DV,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0035, "Stick Heel/Toe",
		DV,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0036, "Stick Follow Through",
		DV,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0037, "Stick Tempo",
		DV,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0038, "Stick Type",
		NAry,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0039, "Stick Height",
		DV,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0050, "Putter",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0051, "1 Iron",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0052, "2 Iron",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0053, "3 Iron",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0054, "4 Iron",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0055, "5 Iron",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0056, "6 Iron",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0057, "7 Iron",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0058, "8 Iron",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0059, "9 Iron",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x005a, "10 Iron",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x005b, "11 Iron",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x005c, "Sand Wedge",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x005d, "Loft Wedge",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x005e, "Power Wedge",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x005f, "1 Wood",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0060, "3 Wood",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0061, "5 Wood",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0062, "7 Wood",
		Sel,
	},
	{
		HID_USAGE_PAGE_SPORTS,
		0x0063, "9 Wood",
		Sel,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0001, "3D Game Controller",
		CA,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0002, "Pinball Device",
		CA,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0003, "Gun Device",
		CA,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0020, "Point of View",
		CP,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0021, "Turn Right/Left",
		DV,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0022, "Pitch Right/Left",
		DV,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0023, "Roll Forward/Backward",
		DV,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0024, "Move Right/Left",
		DV,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0025, "Move Forward/Backward",
		DV,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0026, "Move Up/Down",
		DV,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0027, "Lean Right/Left",
		DV,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0028, "Lean Forward/Backward",
		DV,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0029, "Height of POV",
		DV,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x002a, "Flipper",
		MC,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x002b, "Secondary Flipper",
		MC,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x002c, "Bump",
		MC,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x002d, "New Game",
		OSC,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x002e, "Shoot Ball",
		OSC,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x002f, "Player",
		OSC,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0030, "Gun Bolt",
		OOC,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0031, "Gun Clip",
		OOC,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0032, "Gun Selector",
		NAry,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0033, "Gun Single Shot",
		Sel,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0034, "Gun Burst",
		Sel,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0035, "Gun Automatic",
		Sel,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0036, "Gun Safety",
		OOC,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0037, "Gamepad Fire/Jump",
		CL,
	},
	{
		HID_USAGE_PAGE_GAME,
		0x0039, "Gamepad Trigger",
		CL,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0000, "Undefined",
		NONE,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0001, "Num Lock",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0002, "Caps Lock",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0003, "Scroll Lock",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0004, "Compose",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0005, "Kana",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0006, "Power",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0007, "Shift",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0008, "Do Not Disturb",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0009, "Mute",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x000a, "Tone Enable",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x000b, "High Cut Filter",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x000c, "Low Cut Filter",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x000d, "Equalizer Enable",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x000e, "Sound Field On",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x000f, "Surround On",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0010, "Repeat",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0011, "Stereo",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0012, "Sampling Rate Detect",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0013, "Spinning",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0014, "CAV",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0015, "CLV",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0016, "Recording Format Detect",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0017, "Off-Hook",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0018, "Ring",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0019, "Message Waiting",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x001a, "Data Mode",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x001b, "Battery Operation",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x001c, "Battery OK",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x001d, "Battery Low",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x001e, "Speaker",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x001f, "Head Set",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0020, "Hold",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0021, "Microphone",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0022, "Coverage",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0023, "Night Mode",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0024, "Send Calls",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0025, "Call Pickup",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0026, "Conference",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0027, "Stand-by",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0028, "Camera On",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0029, "Camera Off",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x002a, "On-Line",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x002b, "Off-Line",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x002c, "Busy",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x002d, "Ready",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x002e, "Paper-Out",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x002f, "Paper-Jam",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0030, "Remote",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0031, "Forward",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0032, "Reverse",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0033, "Stop",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0034, "Rewind",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0035, "Fast Forward",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0036, "Play",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0037, "Pause",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0038, "Record",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0039, "Error",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x003a, "Usage Selected Indicator",
		US,
	},
	{
		HID_USAGE_PAGE_LED,
		0x003b, "Usage In Use Indicator",
		US,
	},
	{
		HID_USAGE_PAGE_LED,
		0x003c, "Usage Multi Mode Indicator",
		UM,
	},
	{
		HID_USAGE_PAGE_LED,
		0x003d, "Indicator On",
		Sel,
	},
	{
		HID_USAGE_PAGE_LED,
		0x003e, "Indicator Flash",
		Sel,
	},
	{
		HID_USAGE_PAGE_LED,
		0x003f, "Indicator Slow Blink",
		Sel,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0040, "Indicator Fast Blink",
		Sel,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0041, "Indicator Off",
		Sel,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0042, "Flash On Time",
		DV,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0043, "Slow Blink On Time",
		DV,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0044, "Slow Blink Off Time",
		DV,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0045, "Fast Blink On Time",
		DV,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0046, "Fast Blink Off Time",
		DV,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0047, "Usage Indicator Color",
		UM,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0048, "Indicator Red",
		Sel,
	},
	{
		HID_USAGE_PAGE_LED,
		0x0049, "Indicator Green",
		Sel,
	},
	{
		HID_USAGE_PAGE_LED,
		0x004a, "Indicator Amber",
		Sel,
	},
	{
		HID_USAGE_PAGE_LED,
		0x004b, "Generic Indicator",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x004c, "System Suspend",
		OOC,
	},
	{
		HID_USAGE_PAGE_LED,
		0x004d, "External Power Connected",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0000, "Undefined",
		NONE,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0001, "Phone",
		CA,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0002, "Answering Machine",
		CA,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0003, "Message Controls",
		CL,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0004, "Handset",
		CL,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0005, "Headset",
		CL,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0006, "Telephony Key Pad",
		NAry,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0007, "Programmable Button",
		NAry,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0020, "Hook Switch",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0021, "Flash",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0022, "Feature",
		OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0023, "Hold",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0024, "Redial",
		OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0025, "Transfer",
		OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0026, "Drop",
		OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0027, "Park",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0028, "Forward Calls",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0029, "Alternate Function",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x002a, "Line",
		OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x002b, "Speaker Phone",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x002c, "Conference",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x002d, "Ring Enable",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x002e, "Ring Select",
		OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x002f, "Phone Mute",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0030, "Caller ID",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0050, "Speed Dial",
		OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0051, "Store Number",
		OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0052, "Recall Number",
		OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0053, "Phone Directory",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0070, "Voice Mail",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0071, "Screen Calls",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0072, "Do Not Disturb",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0073, "Message",
		OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0074, "Answer On/Off",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0090, "Inside Dial Tone",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0091, "Outside Dial Tone",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0092, "Inside Ring Tone",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0093, "Outside Ring Tone",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0094, "Priority Ring Tone",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0095, "Inside Ringback",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0096, "Priority Ringback",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0097, "Line Busy Tone",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0098, "Reorder Tone",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x0099, "Call Waiting Tone",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x009a, "Confirmation Tone 1",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x009b, "Confirmation Tone 2",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x009c, "Tones Off",
		OOC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x009d, "Outside Ringback",
		MC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00b0, "Phone Key 0",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00b1, "Phone Key 1",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00b2, "Phone Key 2",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00b3, "Phone Key 3",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00b4, "Phone Key 4",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00b5, "Phone Key 5",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00b6, "Phone Key 6",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00b7, "Phone Key 7",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00b8, "Phone Key 8",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00b9, "Phone Key 9",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00ba, "Phone Key Star",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00bb, "Phone Key Pound",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00bc, "Phone Key A",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00bd, "Phone Key B",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00be, "Phone Key C",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_TELEPHONY,
		0x00bf, "Phone Key D",
		Sel|OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0000, "Undefined",
		NONE,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0001, "Consumer Control",
		CA,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0002, "Numeric Key Pad",
		NAry,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0003, "Programmable Buttons",
		NAry,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0020, "+10",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0021, "+100",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0022, "AM/PM",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0030, "Power",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0031, "Reset",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0032, "Sleep",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0033, "Sleep After",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0034, "Sleep Mode",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0035, "Illumination",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0036, "Function Buttons",
		NAry,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0040, "Menu",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0041, "Menu Pick",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0042, "Menu Up",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0043, "Menu Down",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0044, "Menu Left",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0045, "Menu Right",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0046, "Menu Escape",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0047, "Menu Value Increase",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0048, "Menu Value Decrease",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0060, "Data On Screen",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0061, "Closed Caption",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0062, "Closed Caption Select",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0063, "VCR/TV",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0064, "Broadcast Mode",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0065, "Snapshot",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0066, "Still",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0080, "Selection",
		NAry,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0081, "Assign Selection",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0082, "Mode Step",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0083, "Recall Last",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0084, "Enter Channel",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0085, "Order Movie",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0086, "Channel",
		LC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0087, "Media Selection",
		NAry,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0088, "Media Select Computer",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0089, "Media Select TV",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x008a, "Media Select WWW",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x008b, "Media Select DVD",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x008c, "Media Select Telephone",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x008d, "Media Select Program Guide",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x008e, "Media Select Video Phone",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x008f, "Media Select Games",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0090, "Media Select Messages",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0091, "Media Select CD",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0092, "Media Select VCR",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0093, "Media Select Tuner",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0094, "Quit",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0095, "Help",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0096, "Media Select Tape",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0097, "Media Select Cable",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0098, "Media Select Satellite",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0099, "Media Select Security",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x009a, "Media Select Home",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x009b, "Media Select Call",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x009c, "Channel Increment",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x009d, "Channel Decrement",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x009e, "Media Select SAP",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00a0, "VCR Plus",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00a1, "Once",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00a2, "Daily",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00a3, "Weekly",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00a4, "Monthly",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00b0, "Play",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00b1, "Pause",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00b2, "Record",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00b3, "Fast Forward",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00b4, "Rewind",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00b5, "Scan Next Track",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00b6, "Scan Previous Track",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00b7, "Stop",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00b8, "Eject",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00b9, "Random Play",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00ba, "Select Disc",
		NAry,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00bb, "Enter Disc",
		MC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00bc, "Repeat",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00bd, "Tracking",
		LC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00be, "Track Normal",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00bf, "Slow Tracking",
		LC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00c0, "Frame Forward",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00c1, "Frame Back",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00c2, "Mark",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00c3, "Clear Mark",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00c4, "Repeat From Mark",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00c5, "Return To Mark",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00c6, "Search Mark Forward",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00c7, "Search Mark Backwards",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00c8, "Counter Reset",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00c9, "Show Counter",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00ca, "Tracking Increment",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00cb, "Tracking Decrement",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00cc, "Stop/Eject",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00cd, "Play/Pause",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00ce, "Play/Skip",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00e0, "Volume",
		LC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00e1, "Balance",
		LC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00e2, "Mute",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00e3, "Bass",
		LC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00e4, "Treble",
		LC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00e5, "Bass Boost",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00e6, "Surround Mode",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00e7, "Loudness",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00e8, "MPX",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00e9, "Volume Increment",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00ea, "Volume Decrement",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00f0, "Speed Select",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00f1, "Playback Speed",
		NAry,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00f2, "Standard Play",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00f3, "Long Play",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00f4, "Extended Play",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x00f5, "Slow",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0100, "Fan Enable",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0101, "Fan Speed",
		LC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0102, "Light Enable",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0103, "Light Illumination Level",
		LC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0104, "Climate Control Enable",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0105, "Room Temperature",
		LC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0106, "Security Enable",
		OOC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0107, "Fire Alarm",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0108, "Police Alarm",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0150, "Balance Right",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0151, "Balance Left",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0152, "Bass Increment",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0153, "Bass Decrement",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0154, "Treble Increment",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0155, "Treble Decrement",
		RTC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0160, "Speaker System",
		CL,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0161, "Channel Left",
		CL,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0162, "Channel Right",
		CL,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0163, "Channel Center",
		CL,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0164, "Channel Front",
		CL,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0165, "Channel Center Front",
		CL,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0166, "Channel Side",
		CL,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0167, "Channel Surround",
		CL,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0168, "Channel Low Frequency Enhancement",
		CL,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0169, "Channel Top",
		CL,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x016a, "Channel Unknown",
		CL,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0170, "Sub-channel",
		LC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0171, "Sub-channel Increment",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0172, "Sub-channel Decrement",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0173, "Alternate Audio Increment",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0174, "Alternate Audio Decrement",
		OSC,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0180, "Application Launch Buttons",
		NAry,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0181, "AL Launch Button Configuration Tool",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0182, "AL Programmable Button Configuration",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0183, "AL Consumer Control Configuration",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0184, "AL Word Processor",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0185, "AL Text Editor",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0186, "AL Spreadsheet",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0187, "AL Graphics Editor",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0188, "AL Presentation App",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0189, "AL Database App",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x018a, "AL Email Reader",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x018b, "AL Newsreader",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x018c, "AL Voicemail",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x018d, "AL Contacts/Address Book",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x018e, "AL Calendar/Schedule",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x018f, "AL Task/Project Manager",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0190, "AL Log/Journal/Timecard",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0191, "AL Checkbook/Finance",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0192, "AL Calculator",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0193, "AL A/V Capture/Playback",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0194, "AL Local Machine Browser",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0195, "AL LAN/WAN Browser",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0196, "AL Internet Browser",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0197, "AL Remote Networking/ISP Connect",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0198, "AL Network Conference",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0199, "AL Network Chat",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x019a, "AL Telephony/Dialer",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x019b, "AL Logon",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x019c, "AL Logoff",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x019d, "AL Logon/Logoff",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x019e, "AL Terminal Lock/Screensaver",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x019f, "AL Control Panel",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x01a0, "AL Command Line Processor/Run",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x01a1, "AL Process/Task Manager",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x01a2, "AL Select Task/Application",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0143, "AL Next Task/Application",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x01a4, "AL Previous Task/Application",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x01a5, "AL Preemptive Halt Task/Application",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0200, "Generic GUI Application Controls",
		NAry,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0201, "AC New",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0202, "AC Open",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0203, "AC Close",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0204, "AC Exit",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0205, "AC Maximize",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0206, "AC Minimize",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0207, "AC Save",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0208, "AC Print",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0209, "AC Properties",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x021a, "AC Undo",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x021b, "AC Copy",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x021c, "AC Cut",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x021d, "AC Paste",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x021e, "AC Select All",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x021f, "AC Find",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0220, "AC Find and Replace",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0221, "AC Search",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0222, "AC Go To",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0223, "AC Home",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0224, "AC Back",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0225, "AC Forward",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0226, "AC Stop",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0227, "AC Refresh",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0228, "AC Previous Link",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0229, "AC Next Link",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x022a, "AC Bookmarks",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x022b, "AC History",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x022c, "AC Subscriptions",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x022d, "AC Zoom In",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x022e, "AC Zoom Out",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x022f, "AC Zoom",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0230, "AC Full Screen View",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0231, "AC Normal View",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0232, "AC View Toggle",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0233, "AC Scroll Up",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0234, "AC Scroll Down",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0235, "AC Scroll",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0236, "AC Pan Left",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0237, "AC Pan Right",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0238, "AC Pan",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x0239, "AC New Window",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x023a, "AC Tile Horizontally",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x023b, "AC Tile Vertically",
		Sel,
	},
	{
		HID_USAGE_PAGE_CONSUMER,
		0x023c, "AC Format",
		Sel,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0000, "Undefined",
		NONE,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0001, "Digitizer",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0002, "Pen",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0003, "Light Pen",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0004, "Touch Screen",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0005, "Touch Pad",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0006, "White Board",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0007, "Coordinate Measuring Machine",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0008, "3D Digitizer",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0009, "Stereo Plotter",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x000a, "Articulated Arm",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x000b, "Armature",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x000c, "Multiple Point Digitizer",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x000d, "Free Space Wand",
		CA,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0020, "Stylus",
		CL,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0021, "Puck",
		CL,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0022, "Finger",
		CL,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0030, "Tip Pressure",
		DV,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0031, "Barrel Pressure",
		DV,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0032, "In Range",
		MC,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0033, "Touch",
		MC,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0034, "Untouch",
		OSC,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0035, "Tap",
		OSC,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0036, "Quality",
		DV,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0037, "Data Valid",
		MC,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0038, "Transducer Index",
		DV,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0039, "Tablet Function Keys",
		CL,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x003a, "Program Change Keys",
		CL,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x003b, "Battery Strength",
		DV,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x003c, "Invert",
		MC,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x003d, "X Tilt",
		DV,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x003e, "Y Tilt",
		DV,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x003f, "Azimuth",
		DV,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0040, "Altitude",
		DV,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0041, "Twist",
		DV,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0042, "Tip Switch",
		MC,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0043, "Secondary Tip Switch",
		MC,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0044, "Barrel Switch",
		MC,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0045, "Eraser",
		MC,
	},
	{
		HID_USAGE_PAGE_DIGITIZER,
		0x0046, "Tablet Pick",
		MC,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0000, "Undefined",
		NONE,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0001, "Physical Interface Device",
		CA,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0020, "Normal",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0021, "Set Effect Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0022, "Effect Block Index",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0023, "Parameter Block Offset",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0024, "ROM Flag",
		DF,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0025, "Effect Type",
		NAry,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0026, "ET Constant Force",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0027, "ET Ramp",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0028, "ET Custom Force Data",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0030, "ET Square",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0031, "ET Sine",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0032, "ET Triangle",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0033, "ET Sawtooth Up",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0034, "ET Sawtooth Down",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0040, "ET Spring",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0041, "ET Damper",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0042, "ET Inertia",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0043, "ET Friction",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0050, "Duration",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0051, "Sample Period",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0052, "Gain",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0053, "Trigger Button",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0054, "Trigger Repeat Interval",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0055, "Axes Enable",
		US,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0056, "Direction Enable",
		DF,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0057, "Direction",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0058, "Type Specific Block Offset",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0059, "Block Type",
		NAry,
	},
	{
		HID_USAGE_PAGE_PID,
		0x005a, "Set Envelope Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x005b, "Attack Level",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x005c, "Attack Time",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x005d, "Fade Level",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x005e, "Fade Time",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x005f, "Set Condition Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0060, "CP Offset",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0061, "Positive Coefficient",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0062, "Negative Coefficient",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0063, "Positive Saturation",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0064, "Negative Saturation",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0065, "Dead Band",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0066, "Download Force Sample",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0067, "Isoch Custom Force Enable",
		NONE,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0068, "Custom Force Data Report",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0069, "Custom Force Data",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x006a, "Custom Force Vendor Defined Data",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x00a6, "Actuator Power",
		OOC,
	},
	{
		HID_USAGE_PAGE_PID,
		0x006b, "Set Custom Force Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x006c, "Custom Force Data Offset",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x006d, "Sample Count",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x006e, "Set Periodic Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x006f, "Offset",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0070, "Magnitude",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0071, "Phase",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0072, "Period",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0073, "Set Constant Force Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0074, "Set Ramp Force Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0075, "Ramp Start",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0076, "Ramp End",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0077, "Effect Operation Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0078, "Effect Operation",
		NAry,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0079, "Op Effect Start",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x007a, "Op Effect Start Solo",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x007b, "Op Effect Stop",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x007c, "Loop Count",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x007d, "Device Gain Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x007e, "Device Gain",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x007f, "PID Pool Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0080, "RAM Pool Size",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0081, "ROM Pool Size",
		SV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0082, "ROM Effect Block Count",
		SV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0083, "Simultaneous Effects Max",
		SV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0084, "Pool Alignment",
		SV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0085, "PID Pool Move Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0086, "Move Source",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0087, "Move Destination",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0088, "Move Length",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0089, "PID Block Load Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x008b, "Block Load Status",
		NAry,
	},
	{
		HID_USAGE_PAGE_PID,
		0x008c, "Block Load Success",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x008d, "Block Load Full",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x008e, "Block Load Error",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x008f, "Block Handle",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0090, "PID Block Free Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0091, "Type Specific Block Handle",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0092, "PID State Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0093, "PID Effect State ?",
		NAry,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0094, "Effect Playing",
		DF,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0095, "PID Device Control Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0096, "PID Device Control",
		NAry,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0097, "DC Enable Actuators",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0098, "DC Disable Actuators",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x0099, "DC Stop All Effects",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x009a, "DC Device Reset",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x009b, "DC Device Pause",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x009c, "DC Device Continue",
		Sel,
	},
	{
		HID_USAGE_PAGE_PID,
		0x009f, "Device Paused",
		DF,
	},
	{
		HID_USAGE_PAGE_PID,
		0x00a0, "Actuators Enabled",
		DF,
	},
	{
		HID_USAGE_PAGE_PID,
		0x00a4, "Safety Switch",
		DF,
	},
	{
		HID_USAGE_PAGE_PID,
		0x00a5, "Actuator Override Switch",
		DF,
	},
	{
		HID_USAGE_PAGE_PID,
		0x00a6, "Actuator Power",
		OOC,
	},
	{
		HID_USAGE_PAGE_PID,
		0x00a7, "Start Delay",
		DV,
	},
	{
		HID_USAGE_PAGE_PID,
		0x00a8, "Parameter Block Size",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x00a9, "Device Managed Pool",
		SF,
	},
	{
		HID_USAGE_PAGE_PID,
		0x00aa, "Shared Parameter Blocks",
		SF,
	},
	{
		HID_USAGE_PAGE_PID,
		0x00ab, "Create New Effect Report",
		CL,
	},
	{
		HID_USAGE_PAGE_PID,
		0x00ac, "RAM Pool Available",
		DV,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0000, "Undefined",
		NONE,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0001, "Alphanumeric Display",
		CA,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0020, "Display Attributes Report",
		CL,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0021, "ASCII Character Set",
		SF,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0022, "Data Read Back",
		SF,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0023, "Font Read Back",
		SF,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0024, "Display Control Report",
		CL,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0025, "Clear Display",
		DF,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0026, "Display Enable",
		DF,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0027, "Screen Saver Delay",
		SV|DV,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0028, "Screen Saver Enable",
		DF,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0029, "Vertical Scroll",
		SF|DF,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x002a, "Horizontal Scroll",
		SF|DF,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x002b, "Character Report",
		CL,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x002c, "Display Data",
		DV,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x002d, "Display Status",
		CL,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x002e, "Stat Not Ready",
		Sel,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x002f, "Stat Ready",
		Sel,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0030, "Err Not a loadable character",
		Sel,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0031, "Err Font data cannot be read",
		Sel,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0032, "Cursor Position Report",
		CL,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0033, "Row",
		DV,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0034, "Column",
		DV,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0035, "Rows",
		SV,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0036, "Columns",
		SV,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0037, "Cursor Pixel Positioning",
		SF,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0038, "Cursor Mode",
		DF,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0039, "Cursor Enable",
		DF,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x003a, "Cursor Blink",
		DF,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x003b, "Font Report",
		CL,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x003c, "Font Data",
		NONE,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x003d, "Character Width",
		SV,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x003e, "Character Height",
		SV,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x003f, "Character Spacing Horizontal",
		SV,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0040, "Character Spacing Vertical",
		SV,
	},
	{
		HID_USAGE_PAGE_ALPHANUMERIC,
		0x0041, "Unicode Character Set",
		SF,
	},
	{
		HID_USAGE_PAGE_BARCODE,
		0x0000, "Undefined",
		NONE,
	},
	{
		HID_USAGE_PAGE_BARCODE,
		0x0001, "Bar Code Badge Reader",
		CA,
	},
	{ 0xffff, 0xffff, NULL, NONE, }
};
